name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  # Executa diariamente às 18:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run 3D Contribution Graph Generator
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Atualizando gráfico 3D de contribuições" || echo "Nada para commitar"
          git pull --rebase
          git push || echo "Push falhou (talvez sem alterações)"

